# Translations template for cinder.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the cinder project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: cinder 2015.1.dev28\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-26 06:07+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: cinder/quota_utils.py:49
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG volume - "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/quota_utils.py:60 cinder/transfer/api.py:173
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create volume (%(d_consumed)d "
"volumes already consumed)"
msgstr ""

#: cinder/service.py:91
msgid ""
"OSProfiler is enabled.\n"
"It means that person who knows any of hmac_keys that are specified in "
"/etc/cinder/api-paste.ini can trace his requests. \n"
"In real life only operator can read this file so there is no security "
"issue. Note that even if person can trigger profiler, only admin user can"
" retrieve trace information.\n"
"To disable OSprofiler set in cinder.conf:\n"
"[profiler]\n"
"enabled=false"
msgstr ""

#: cinder/service.py:191
#, python-format
msgid ""
"Report interval must be less than service down time. Current config "
"service_down_time: %(service_down_time)s, report_interval for this: "
"service is: %(report_interval)s. Setting global service_down_time to: "
"%(new_down_time)s"
msgstr ""

#: cinder/service.py:259
msgid "Service killed that has no database entry"
msgstr ""

#: cinder/api/__init__.py:31
msgid ""
"The v1 api is deprecated and will be removed in the Liberty release. You "
"should set enable_v1_api=false and enable_v2_api=true in your cinder.conf"
" file."
msgstr ""

#: cinder/api/extensions.py:276
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: cinder/api/extensions.py:345
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: cinder/api/extensions.py:370
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr ""

#: cinder/api/openstack/__init__.py:114
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: cinder/backup/api.py:153
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG backup "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/backup/api.py:165
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create backups (%(d_consumed)d "
"backups already consumed)"
msgstr ""

#: cinder/backup/chunkeddriver.py:673
msgid "swift error while listing objects, continuing with delete."
msgstr ""

#: cinder/backup/driver.py:212
msgid ""
"Destination volume type is different from source volume type for an "
"encrypted volume. Encrypted backup restore has failed."
msgstr ""

#: cinder/backup/manager.py:620
#, python-format
msgid ""
"Backup service %(service)s does not support verify. Backup id %(id)s is "
"not verified. Skipping verify."
msgstr ""

#: cinder/backup/drivers/ceph.py:1188
#, python-format
msgid ""
"RBD image for backup %(backup)s of volume %(volume)s not found. Deleting "
"backup metadata."
msgstr ""

#: cinder/brick/initiator/connector.py:308
msgid "Failed to login to any of the iSCSI targets."
msgstr ""

#: cinder/brick/initiator/connector.py:321
#, python-format
msgid ""
"ISCSI volume not yet found at: %(host_devices)s. Will rescan & retry.  "
"Try number: %(tries)s"
msgstr ""

#: cinder/brick/initiator/connector.py:562
#, python-format
msgid ""
"Failed to login iSCSI target %(iqn)s on portal %(portal)s (exit code "
"%(err)s)."
msgstr ""

#: cinder/brick/initiator/connector.py:726
#, python-format
msgid "Fibre volume not yet found. Will rescan & retry.  Try number: %(tries)s"
msgstr ""

#: cinder/brick/initiator/connector.py:980
#, python-format
msgid "AoE volume not yet found at: %(path)s. Try number: %(tries)s"
msgstr ""

#: cinder/brick/initiator/connector.py:1062
msgid ""
"Connection details not present. RemoteFsClient may not initialize "
"properly."
msgstr ""

#: cinder/brick/initiator/linuxfc.py:51 cinder/brick/initiator/linuxfc.py:57
msgid "systool is not installed"
msgstr ""

#: cinder/brick/initiator/linuxfc.py:187
#, python-format
msgid "unit_add call for s390 failed exit (%(code)s), stderr (%(stderr)s)"
msgstr ""

#: cinder/brick/initiator/linuxfc.py:210
#, python-format
msgid "unit_remove call for s390 failed exit (%(code)s), stderr (%(stderr)s)"
msgstr ""

#: cinder/brick/initiator/linuxscsi.py:118
#: cinder/brick/initiator/linuxscsi.py:126
#: cinder/brick/initiator/linuxscsi.py:143
#, python-format
msgid "multipath call failed exit (%(code)s)"
msgstr ""

#: cinder/brick/initiator/linuxscsi.py:166
#, python-format
msgid "Couldn't find multipath device %(line)s"
msgstr ""

#: cinder/common/sqlalchemyutils.py:67
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: cinder/consistencygroup/api.py:101
#, python-format
msgid "Availability zone '%s' is invalid"
msgstr ""

#: cinder/db/sqlalchemy/api.py:221
#, python-format
msgid "Deadlock detected when running '%(func_name)s': Retrying..."
msgstr ""

#: cinder/db/sqlalchemy/api.py:874
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: cinder/image/glance.py:133
msgid ""
"glance_num_retries shouldn't be a negative value. The number of retries "
"will be set to 0 until this iscorrected in the cinder.conf."
msgstr ""

#: cinder/image/image_utils.py:72 cinder/volume/drivers/smbfs.py:249
msgid "qemu-img is not installed."
msgstr ""

#: cinder/keymgr/conf_key_mgr.py:79
msgid ""
"config option keymgr.fixed_key has not been defined: some operations may "
"fail unexpectedly"
msgstr ""

#: cinder/keymgr/conf_key_mgr.py:135
#, python-format
msgid "Not deleting key %s"
msgstr ""

#: cinder/openstack/common/loopingcall.py:87
#, python-format
msgid "task %(func_name)r run outlasted interval by %(delay).2f sec"
msgstr ""

#: cinder/openstack/common/service.py:355
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:409
#, python-format
msgid "No weighed hosts found for volume with properties: %s"
msgstr ""

#: cinder/scheduler/host_manager.py:486
#, python-format
msgid "volume service is down. (host: %s)"
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:71
#, python-format
msgid ""
"Insufficient free space for volume creation. Total capacity is "
"%(total).2f on host %(host)s."
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:84
#, python-format
msgid ""
"Insufficient free space for volume creation on host %(host)s (requested /"
" avail): %(requested)s/%(available)s"
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:102
#, python-format
msgid ""
"Insufficient free space for thin provisioning. The ratio of provisioned "
"capacity over total capacity %(provisioned_ratio).2f has exceeded the "
"maximum over subscription ratio %(oversub_ratio).2f on host %(host)s."
msgstr ""

#: cinder/scheduler/filters/driver_filter.py:56
msgid ""
"No 'volume_backend_name' key in extra_specs. Skipping volume backend name"
" check."
msgstr ""

#: cinder/scheduler/filters/driver_filter.py:60
#, python-format
msgid ""
"Volume backend names do not match: '%(target)s' vs '%(current)s' :: "
"Skipping"
msgstr ""

#: cinder/scheduler/filters/driver_filter.py:67
msgid "Filter function not set :: passing host"
msgstr ""

#: cinder/scheduler/filters/driver_filter.py:76
#, python-format
msgid "Error in filtering function '%(function)s' : '%(error)s' :: failing host"
msgstr ""

#: cinder/scheduler/filters/instance_locality_filter.py:97
#, python-format
msgid "Hint \"%s\" dropped because ExtendedServerAttributes not active in Nova."
msgstr ""

#: cinder/scheduler/filters/instance_locality_filter.py:108
#, python-format
msgid ""
"Hint \"%s\" dropped because Nova did not return enough information. "
"Either Nova policy needs to be changed or a privileged account for Nova "
"should be specified in conf."
msgstr ""

#: cinder/scheduler/weights/goodness.py:54
msgid "Goodness function not set :: defaulting to minimal goodness rating of 0"
msgstr ""

#: cinder/scheduler/weights/goodness.py:62
#, python-format
msgid ""
"Error in goodness_function function '%(function)s' : '%(error)s' :: "
"Defaulting to a goodness of 0"
msgstr ""

#: cinder/scheduler/weights/goodness.py:73
#, python-format
msgid ""
"Invalid goodness result.  Result must be between 0 and 100.  Result "
"generated: '%s' :: Defaulting to a goodness of 0"
msgstr ""

#: cinder/tests/test_netapp_nfs.py:375
#, python-format
msgid "Share %(share)s and file name %(file_name)s"
msgstr ""

#: cinder/transfer/api.py:161
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG volume "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/volume/api.py:636 cinder/volume/api.py:770
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG snapshot "
"(%(d_consumed)dG of %(d_quota)dG already consumed)."
msgstr ""

#: cinder/volume/api.py:648 cinder/volume/api.py:782
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create snapshot (%(d_consumed)d "
"snapshots already consumed)."
msgstr ""

#: cinder/volume/driver.py:392
#, python-format
msgid "Failed to activate volume copy throttling: %(err)s"
msgstr ""

#: cinder/volume/driver.py:1378 cinder/volume/targets/iscsi.py:164
msgid "ISCSI provider_location not stored, using discovery"
msgstr ""

#: cinder/volume/manager.py:205
#, python-format
msgid "Driver path %s is deprecated, update your configuration to the new path."
msgstr ""

#: cinder/volume/manager.py:936
#, python-format
msgid "Deleting image %(image_id)s in %(image_status)s state."
msgstr ""

#: cinder/volume/manager.py:942
#, python-format
msgid "Error occurred while deleting image %s."
msgstr ""

#: cinder/volume/manager.py:1258
#, python-format
msgid ""
"Failed to migrate volume. The destination volume %(vol)s is not deleted "
"since the source volume may have already deleted."
msgstr ""

#: cinder/volume/manager.py:1423
#, python-format
msgid ""
"Unable to update stats, %(driver_name)s -%(driver_version)s "
"%(config_group)s driver is uninitialized."
msgstr ""

#: cinder/volume/qos_specs.py:199
#, python-format
msgid "Failed to associate qos specs %(id)s with type: %(vol_type_id)s"
msgstr ""

#: cinder/volume/qos_specs.py:213
#, python-format
msgid "Failed to disassociate qos specs %(id)s with type: %(vol_type_id)s"
msgstr ""

#: cinder/volume/qos_specs.py:227
#, python-format
msgid "Failed to disassociate qos specs %s."
msgstr ""

#: cinder/volume/throttling.py:86
#, python-format
msgid "Failed to setup blkio cgroup to throttle the device '%(device)s'."
msgstr ""

#: cinder/volume/drivers/datera.py:107
msgid ""
"Client cert verification and datera_api_token are deprecated in the "
"Datera driver, and will be removed in the Liberty release. Please set the"
" san_login and san_password in your cinder.conf instead."
msgstr ""

#: cinder/volume/drivers/eqlx.py:148
msgid ""
"Configuration options eqlx_use_chap, eqlx_chap_login and "
"eqlx_chap_password are deprecated. Use use_chap_auth, chap_username and "
"chap_password respectively for the same."
msgstr ""

#: cinder/volume/drivers/eqlx.py:417
#, python-format
msgid "Volume %s was not found while trying to delete it."
msgstr ""

#: cinder/volume/drivers/eqlx.py:532
#, python-format
msgid "Volume %s is not found!, it may have been deleted."
msgstr ""

#: cinder/volume/drivers/glusterfs.py:184
#, python-format
msgid "Failed to refresh mounts, reason=%s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:273 cinder/volume/drivers/quobyte.py:190
#: cinder/volume/drivers/remotefs.py:227
#, python-format
msgid "Volume %s does not have provider_location specified, skipping"
msgstr ""

#: cinder/volume/drivers/lvm.py:175
#, python-format
msgid "Unable to update stats on non-initialized Volume Group: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:357 cinder/volume/drivers/srb.py:770
#, python-format
msgid "snapshot: %s not found, skipping delete operations"
msgstr ""

#: cinder/volume/drivers/lvm.py:634
msgid ""
"LVMISCSIDriver is deprecated, you should now just use LVMVolumeDriver and"
" specify target_helper for the target driver you wish to use."
msgstr ""

#: cinder/volume/drivers/lvm.py:651
msgid ""
"LVMISERDriver is deprecated, you should now just use LVMVolumeDriver and "
"specify target_helper for the target driver you wish to use. In order to "
"enable iser, please set iscsi_protocol with the value iser."
msgstr ""

#: cinder/volume/drivers/nfs.py:340 cinder/volume/drivers/remotefs.py:519
#, python-format
msgid ""
"The NAS file permissions mode will be 666 (allowing other/world read & "
"write access). This is considered an insecure NAS environment. Please see"
" %s for information on a secure NFS configuration."
msgstr ""

#: cinder/volume/drivers/nfs.py:361 cinder/volume/drivers/remotefs.py:512
#, python-format
msgid ""
"The NAS file operations will be run as root: allowing root level access "
"at the storage backend. This is considered an insecure NAS environment. "
"Please see %s for information on a secure NAS configuration."
msgstr ""

#: cinder/volume/drivers/pure.py:216
#, python-format
msgid "Volume deletion failed with message: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:282
#, python-format
msgid ""
"iSCSI discovery of port %(port_name)s at %(port_portal)s failed with "
"error: %(err_msg)s"
msgstr ""

#: cinder/volume/drivers/pure.py:386
#, python-format
msgid "Volume connection already exists with message: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:549
#, python-format
msgid "Unable to delete Protection Group: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:621
#, python-format
msgid "Unable to delete Protection Group Snapshot: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:723
#, python-format
msgid "Volume unmanage was unable to rename the volume, error message: %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:105
#, python-format
msgid ""
"There's no Quobyte volume configured (%s). Example: quobyte://<DIR "
"host>/<volume name>"
msgstr ""

#: cinder/volume/drivers/quobyte.py:335
#, python-format
msgid "Exception during mounting %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:394
#, python-format
msgid "Failed to unmount previous mount: %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:398
#, python-format
msgid "Unknown error occurred while checking mount point: %s Trying to continue."
msgstr ""

#: cinder/volume/drivers/quobyte.py:416 cinder/volume/drivers/remotefs.py:479
#, python-format
msgid "%s is already mounted"
msgstr ""

#: cinder/volume/drivers/quobyte.py:435
#, python-format
msgid "Volume is not writable. Please broaden the file permissions. Mount: %s"
msgstr ""

#: cinder/volume/drivers/rbd.py:178
msgid "flush() not supported in this version of librbd"
msgstr ""

#: cinder/volume/drivers/rbd.py:830
msgid "volume_tmp_dir is now deprecated, please use image_conversion_dir"
msgstr ""

#: cinder/volume/drivers/remotefs.py:305
#, python-format
msgid "%(path)s is being set with open permissions: %(perm)s"
msgstr ""

#: cinder/volume/drivers/smbfs.py:227 cinder/volume/drivers/ibm/ibmnas.py:288
#, python-format
msgid "Volume %s does not have provider_location specified, skipping."
msgstr ""

#: cinder/volume/drivers/solidfire.py:448
#, python-format
msgid "More than one valid preset was detected, using %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:635
msgid "Requested image is not accesible by current Tenant."
msgstr ""

#: cinder/volume/drivers/srb.py:89
#, python-format
msgid "Retrying failed call to %(func)s, attempt %(attempt)i."
msgstr ""

#: cinder/volume/drivers/srb.py:367
#, python-format
msgid "%s is not an accepted REST server IP address"
msgstr ""

#: cinder/volume/drivers/srb.py:376
msgid "Configuration variable srb_base_urls not set or empty."
msgstr ""

#: cinder/volume/drivers/srb.py:623
#, python-format
msgid "All attempts to recover failed detach of %(volume)s failed."
msgstr ""

#: cinder/volume/drivers/srb.py:687
#, python-format
msgid "Removed volume group %s still appears in vgs."
msgstr ""

#: cinder/volume/drivers/srb.py:886
#, python-format
msgid "Volume %r not found while trying to remove."
msgstr ""

#: cinder/volume/drivers/srb.py:889
#, python-format
msgid "Error while removing export: %r"
msgstr ""

#: cinder/volume/drivers/xio.py:472
#, python-format
msgid "IOnetworks GET failed (%d)"
msgstr ""

#: cinder/volume/drivers/xio.py:602
#, python-format
msgid "Could not get status for %(name)s (%(status)d)."
msgstr ""

#: cinder/volume/drivers/xio.py:610
msgid "No volume node in XML content."
msgstr ""

#: cinder/volume/drivers/xio.py:618
#, python-format
msgid "No status payload for volume %s."
msgstr ""

#: cinder/volume/drivers/xio.py:708
#, python-format
msgid "Volume %(name)s already presented (%(status)d)!"
msgstr ""

#: cinder/volume/drivers/xio.py:985
#, python-format
msgid "Could not get pool information (%s)!"
msgstr ""

#: cinder/volume/drivers/xio.py:1225
#, python-format
msgid "Delete volume: %s not found!"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:226
#, python-format
msgid "Logout error: %(c)d %(r)s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:465
#, python-format
msgid "delete_volume: unable to find volume %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:521
#, python-format
msgid "ScServerOperatingSystem GetList return: %(c)d %(r)s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:787
msgid "Inconsistent Luns."
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_common.py:157
#, python-format
msgid "Unable to locate volume:%s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:676
msgid ""
"The VMAX plugin only supports Retype. If a pool based migration is "
"necessary this will happen on a Retype From the command line: cinder "
"--os-volume-api-version 2 retype <volumeId> <volumeType> --migration-"
"policy on-demand"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:713
#, python-format
msgid ""
"Failed to migrate: %(volumeName)s from default source storage group for "
"FAST policy: %(sourceFastPolicyName)s. Attempting cleanup... "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:741
#, python-format
msgid ""
"Attempting a rollback of: %(volumeName)s to original pool "
"%(sourcePoolInstanceName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:773
#, python-format
msgid "_migrate_rollback on : %(volumeName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:808
#, python-format
msgid "_migrate_cleanup on : %(volumeName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:1009
#, python-format
msgid ""
"The volume: %(volumename)s was not first part of the default storage "
"group for FAST policy %(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:1101
#, python-format
msgid "Volume: %(volumeName)s is not currently belonging to any storage group."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:2129
#, python-format
msgid ""
"Pre check for deletion. Volume: %(volumeName)s is part of a storage "
"group. Attempting removal from %(storageGroupInstanceNames)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:2816
#, python-format
msgid ""
"Volume: %(volume)s with size: %(volumeSize)s bits is not in the "
"Performance Capacity range: %(minimumVolumeSize)s-%(maximumVolumeSize)s "
"bits. for SLO:%(slo)s and workload:%(workload)s. Unpredictable results "
"may occur."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3009
#, python-format
msgid "Volume : %(volumeName)s is not currently belonging to any storage group."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3311
#, python-format
msgid ""
"The volume: %(volumename)s. was not first part of the default storage "
"group for FAST policy %(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fast.py:138
#: cinder/volume/drivers/emc/emc_vmax_masking.py:106
#, python-format
msgid ""
"Volume: %(volumeName)s Does not belong to storage storage group "
"%(defaultSgGroupName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fast.py:409
msgid "Unable to get storage tiers from tier policy rule."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fc.py:227
#, python-format
msgid "Volume %(volume)s is not in any masking view."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:475
#, python-format
msgid "Volume: %(volumeName)s is already part of storage group %(sgGroupName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1045
#: cinder/volume/drivers/emc/emc_vmax_masking.py:1303
#, python-format
msgid "Unable to find Masking view: %(view)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1208
#, python-format
msgid ""
"No storage group found. Performing rollback on Volume: %(volumeName)s To "
"return it to the default storage group for FAST policy "
"%(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1570
#, python-format
msgid ""
"Volume %(volumeName)s was not first part of the default storage group for"
" the FAST Policy."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1721
#, python-format
msgid ""
"Only one volume remains in storage group %(sgname)s. Driver will attempt "
"cleanup."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1727
#, python-format
msgid "Unable to get masking view %(maskingView)s from storage group."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:2041
#, python-format
msgid "No target ports found in masking view %(maskingView)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:2095
#: cinder/volume/drivers/emc/emc_vmax_masking.py:2114
#, python-format
msgid "No port group found in masking view %(mv)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1413
#, python-format
msgid "Storage sync name not found for target %(target)s on %(storageSystem)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1452
#, python-format
msgid ""
"Group sync name not found for target group %(target)s on "
"%(storageSystem)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:410
#, python-format
msgid "LUN already exists, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:447
#, python-format
msgid "LUN is already deleted, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:517
#, python-format
msgid "LUN %(name)s is already expanded. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:571
#, python-format
msgid "Consistency group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:663
#, python-format
msgid "CG %(cg_name)s does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:667
#, python-format
msgid "CG %(cg_name)s is deleting. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:692
#, python-format
msgid "Cgsnapshot name %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:709
#, python-format
msgid "Snapshot %(name)s for consistency group does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:729
#, python-format
msgid "Snapshot %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:749
#, python-format
msgid "Snapshot %(name)s may deleted already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:756
#, python-format
msgid "Snapshot %(name)s is in use, retry. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:783
#, python-format
msgid "Mount point %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:801
#, python-format
msgid ""
"Snapshot %(snapname)s is attached to snapshot mount point %(mpname)s "
"already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:822
#, python-format
msgid "The specified Snapshot mount point %s is not currently attached."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:854
#, python-format
msgid ""
"Migration command may get network timeout. Double check whether migration"
" in fact started successfully. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:866
#, python-format
msgid "Start migration failed. Message: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:869
#, python-format
msgid "Delete temp LUN after migration start failed. LUN: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:953
#, python-format
msgid "Storage group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:969
#, python-format
msgid ""
"Storage group %(name)s doesn't exist, may have already been deleted. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:999
#, python-format
msgid ""
"Host %(host)s has already disconnected from storage group %(sgname)s. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1036
#, python-format
msgid "HLU %(hlu)s has already been removed from %(sgname)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1200
msgid "No array serial number returned, set as unknown."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1230
#, python-format
msgid "Storage Group %s is not found."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1371
#, python-format
msgid "See unavailable iSCSI target: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1617
msgid ""
"destroy_empty_storage_group: True. Empty storage group will be deleted "
"after volume is detached."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1633
msgid "force_delete_lun_in_storagegroup=True"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1709
msgid ""
"Extra spec key 'storagetype:pool' is obsoleted since driver version "
"5.1.0. This key will be ignored."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1793
#, python-format
msgid ""
"LUN corresponding to %s is still in some Storage Groups.Try to bring the "
"LUN out of Storage Groups and retry the deletion."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1823
msgid ""
"Failed to get target_pool_name and target_array_serial. 'location_info' "
"is not in host['capabilities']."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1836
msgid "Error on parsing target_pool_name/target_array_serial."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1850
msgid ""
"Didn't get the pool information of the host %(s). Storage assisted "
"Migration is not supported. The host may be using a legacy driver."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1935
msgid "Storage-assisted migration failed during retype."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2004
#, python-format
msgid ""
"Maximum number of Pool LUNs, %s, have been created. No more LUN creation "
"can be done."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2271
#, python-format
msgid "LUN with id %(remove_id)s is not present in cg %(cg_name)s, skip it."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2373
#, python-format
msgid "Storage Group %s is not found. Create it."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2438
#, python-format
msgid "Failed to register %(itor)s to SP%(sp)s port %(portid)s because: %(msg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2501
#, python-format
msgid "Failed to extract initiators of %s, so ignore deregistration operation."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2508
#, python-format
msgid "Failed to deregister %(itor)s because: %(msg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2787
#, python-format
msgid "Storage Group %s is not found. terminate_connection() is unnecessary."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2796
#, python-format
msgid "Volume %(vol)s was not in Storage Group %(sg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2818
#, python-format
msgid "Failed to destroy Storage Group %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2824
#, python-format
msgid "Fail to connect host %(host)s back to storage group %(sg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2984
#, python-format
msgid ""
"The source volume is a legacy volume. Create volume in the pool where the"
" source volume %s is created."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3039
#, python-format
msgid "CreateSMPTask.revert: delete mount point %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3058
#, python-format
msgid "AttachSnapTask.revert: detach mount point %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3084
#, python-format
msgid "CreateDestLunTask.revert: delete temp lun %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3146
#, python-format
msgid "CreateSnapshotTask.revert: delete temp cgsnapshot %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3151
#, python-format
msgid "CreateSnapshotTask.revert: delete temp snapshot %s"
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:110
#, python-format
msgid "object %(key)s of type %(typ)s not found"
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:446
msgid "terminate_connection: lun map not found"
msgstr ""

#: cinder/volume/drivers/hds/hnas_backend.py:237
#, python-format
msgid "get_evs: %(out)s -- No find for %(fsid)s"
msgstr ""

#: cinder/volume/drivers/hds/hnas_backend.py:272
#, python-format
msgid "get_fsid: %(out)s -- No info for %(fslabel)s"
msgstr ""

#: cinder/volume/drivers/hds/iscsi.py:615
msgid "terminate_conn: provider location empty."
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_common.py:416
#: cinder/volume/drivers/hitachi/hbsd_common.py:423
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1424
#, python-format
msgid "Failed to restart horcm: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_fc.py:183
#, python-format
msgid "Failed to add host group: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_horcm.py:900
#, python-format
msgid "Failed to discard zero page: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1399
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1409
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1417
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1443
#, python-format
msgid "Failed to create pair: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_snm2.py:145
#, python-format
msgid "ldev(%(ldev)d) is already mapped (hlun: %(hlu)d)"
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:370
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:407
#, python-format
msgid "_execute_command_and_parse_attributes: Failed to run command: %s."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:608
#, python-format
msgid "_get_vdisk_map_properties: Did not find a preferred node for vdisk %s."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:850
msgid "_remove_device: invalid properties or device."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:903
#, python-format
msgid ""
"_unmap_vdisk_from_host: No mapping of volume %(vol_name)s to any host "
"found."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:909
#, python-format
msgid ""
"_unmap_vdisk_from_host: Multiple mappings of volume %(vdisk_name)s found,"
" no host specified."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:371
msgid "CHAP secret exists for host but CHAP is disabled"
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:416
#, python-format
msgid "initialize_connection: Did not find a preferred node for volume %s"
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:471
#, python-format
msgid ""
"Unable to find a preferred node match for node %(node)s in the list of "
"available WWPNs on %(host)s. Using first available."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:778
#, python-format
msgid "Volume %s does not exist."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/helpers.py:348
#, python-format
msgid "unmap_vol_from_host: No mapping of volume %(vol_name)s to any host found."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/helpers.py:354
#, python-format
msgid ""
"unmap_vol_from_host: Multiple mappings of volume %(vol_name)s found, no "
"host specified."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/helpers.py:366
#, python-format
msgid ""
"unmap_vol_from_host: No mapping of volume %(vol_name)s to host %(host)s "
"found."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:59
msgid ""
"It is not the recommended way to use drivers by NetApp. Please use "
"NetAppDriver to achieve the functionality."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:131
#, python-format
msgid "Extra spec %(old)s is obsolete.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:136
#, python-format
msgid "Extra spec %(old)s is deprecated.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:127
#, python-format
msgid "Could not determine root volume name on %s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:309
msgid "Volume refresh job already running. Returning..."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:316
#, python-format
msgid "Error refreshing volume info. Message: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_base.py:167
#, python-format
msgid "No entry in LUN table for volume/snapshot %(name)s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:243
#, python-format
msgid ""
"Exception while registering image %(image_id)s in cache. Exception: "
"%(exc)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:311
#, python-format
msgid "Exception during cache cleaning %(share)s. Message - %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:369
#, python-format
msgid "Exception during deleting %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:428
#, python-format
msgid "Unexpected exception during image cloning in share %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:519
msgid "Discover file retries exhausted."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:577
msgid "Unexpected exception while short listing used share."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:640
#, python-format
msgid "Destination %s already exists."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:648
#, python-format
msgid "Exception moving file %(src)s. Message - %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_cmode.py:110
#, python-format
msgid "Exception creating vol %(name)s on share %(share)s. Details: %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_cmode.py:266
msgid "No shares found hence skipping ssc refresh."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:506
msgid "ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:518
msgid "refresh stale ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:621
#, python-format
msgid ""
"The user does not have access or sufficient privileges to use all netapp "
"APIs. The following extra_specs will fail or be ignored: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_7mode.py:129
#, python-format
msgid "Error finding LUNs for volume %s. Verify volume exists."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:110
#, python-format
msgid "Error mapping LUN. Code :%(code)s, Message:%(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:123
#, python-format
msgid "Error unmapping LUN. Code :%(code)s, Message:%(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:333
#, python-format
msgid "Failed to invoke ems. Message : %s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:155
#, python-format
msgid ""
"Production use of \"%(backend)s\" backend requires the Cinder controller "
"to have multipathing properly set up and the configuration option "
"\"%(mpflag)s\" to be set to \"True\"."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:464
msgid "Snapshot volume not found."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:505
#, python-format
msgid "Failure deleting job %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:508
#, python-format
msgid "Volume copy job for src vol %s not found."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:522
#, python-format
msgid "Failure deleting temp snapshot %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:567
#, python-format
msgid "Snapshot %s already deleted."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:674
#, python-format
msgid "Unable to update host type for host with label %(l)s. %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:679
#, python-format
msgid "Message - %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:864
#, python-format
msgid "No storage pool found with available capacity %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:897
msgid "Returning as clean tmp vol job already running."
msgstr ""

#: cinder/volume/drivers/prophetstor/dpl_iscsi.py:154
#, python-format
msgid "Cannot get volume status %(exc)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1176
#, python-format
msgid "Flexvisor failed to delete volume %(id)s from the group %(vgid)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1181
#, python-format
msgid ""
"Flexvisor failed to delete volume %(id)s from group %(vgid)s due to "
"%(status)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1350
#, python-format
msgid "Failed to query pool %(id)s status %(ret)d."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:417
#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:727
#, python-format
msgid "Failed to manage virtual volume %(disp)s due to error during retype."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:1073
msgid ""
"'hp3par:cpg' is not supported as an extra spec in a volume type.  CPG's "
"are chosen by the cinder scheduler, as a pool, from the cinder.conf entry"
" 'hp3par_cpg', which can be a list of CPGs."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:464
msgid ""
"Host exists without CHAP credentials set and has iSCSI attachments but "
"CHAP is enabled.  Updating host with new CHAP credentials."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:497
msgid "Host has no CHAP key, but CHAP is enabled."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:501
msgid "No host or VLUNs exist. Generating new CHAP key."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:529
msgid "Non-iSCSI VLUN detected."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:533
msgid "No VLUN contained CHAP credentials. Generating new CHAP key."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:169
#, python-format
msgid ""
"HPLeftHand API is version %(current)s. A minimum version of %(min)s is "
"needed for manage/unmanage support."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:479
#, python-format
msgid "CHAP secret exists for host %s but CHAP is disabled"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:482
#, python-format
msgid "CHAP is enabled, but server secret not configured on server %s"
msgstr ""

#: cinder/volume/drivers/violin/v6000_common.py:191
#, python-format
msgid "Lun create for %s failed!"
msgstr ""

#: cinder/volume/drivers/violin/v6000_common.py:216
#, python-format
msgid "Lun %s has dependent snapshots, skipping."
msgstr ""

#: cinder/volume/drivers/violin/v6000_fcp.py:442
#: cinder/volume/drivers/violin/v6000_iscsi.py:471
msgid "Failed to receive update for total_gb stat!"
msgstr ""

#: cinder/volume/drivers/violin/v6000_fcp.py:447
#: cinder/volume/drivers/violin/v6000_iscsi.py:476
msgid "Failed to receive update for free_gb stat!"
msgstr ""

#: cinder/volume/drivers/vmware/datastore.py:220
#, python-format
msgid "Unable to fetch datastores connected to host %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:199
msgid ""
"The VMware ESX VMDK driver is now deprecated and will be removed in the "
"Juno release. The VMware vCenter VMDK driver will remain and continue to "
"be supported."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:475
#, python-format
msgid ""
"Ignoring storage profile %s requirement for this volume since policy "
"based placement is disabled."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:631
#, python-format
msgid "Trying to boot from an empty volume: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:904
#, python-format
msgid "Error occurred while deleting temporary disk: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:990
#, python-format
msgid "Error occurred while deleting descriptor: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1019
#, python-format
msgid "Error occurred while deleting backing: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1376
#, python-format
msgid "Volume: %s is in use, can't retype."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1445
#, python-format
msgid ""
"There are no datastores matching new requirements; can't retype volume: "
"%s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1497
#, python-format
msgid ""
"Changing backing: %(backing)s name from %(new_name)s to %(old_name)s "
"failed."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1740
#, python-format
msgid ""
"Cannot undo volume rename; old name was %(old_name)s and new name is "
"%(new_name)s."
msgstr ""

#: cinder/volume/targets/cxt.py:148 cinder/volume/targets/tgt.py:194
#, python-format
msgid "Persistence file already exists for volume, found file at: %s"
msgstr ""

#: cinder/volume/targets/cxt.py:213 cinder/volume/targets/tgt.py:294
#, python-format
msgid "Volume path %s does not exist, nothing to remove."
msgstr ""

#: cinder/volume/targets/iet.py:113
#, python-format
msgid ""
"Failed to find CHAP auth from config for %(vol_id)s. Config file %(conf)s"
" does not exist."
msgstr ""

#: cinder/volume/targets/iet.py:226
#, python-format
msgid ""
"Failed to update %(conf)s for volume id %(vol_id) after removing iscsi "
"target. %(conf)s does not exist."
msgstr ""

#: cinder/volume/targets/iscsi.py:47
#, python-format
msgid ""
"The option %s has been deprecated and no longer has any effect. It will "
"be removed in the Liberty release."
msgstr ""

#: cinder/volume/targets/iser.py:28
msgid ""
"ISERTgtAdm is deprecated, you should now just use LVMVolumeDriver and "
"specify target_helper for the target driver you wish to use. In order to "
"enable iser, please set iscsi_protocol=iser with lioadm or tgtadm target "
"helpers."
msgstr ""

#: cinder/volume/targets/lio.py:37
msgid ""
"The lio_initiator_iqns option has been deprecated and no longer has any "
"effect."
msgstr ""

#: cinder/volume/targets/lio.py:87
#, python-format
msgid ""
"Failed to save iscsi LIO configuration when modifying volume id: "
"%(vol_id)s."
msgstr ""

#: cinder/volume/targets/tgt.py:90
msgid "Attempting recreate of backing lun..."
msgstr ""

#: cinder/volume/targets/tgt.py:222
#, python-format
msgid "Could not create target because it already exists for volume: %s"
msgstr ""

#: cinder/volume/targets/tgt.py:316
#, python-format
msgid ""
"Failed target removal because target or ACL's couldn't be found for iqn: "
"%s."
msgstr ""

#: cinder/volume/targets/tgt.py:335
msgid "Silent failure of target removal detected, retry...."
msgstr ""

#: cinder/zonemanager/utils.py:79
msgid "Driver didn't return connection info, can't add zone."
msgstr ""

#: cinder/zonemanager/utils.py:104
msgid "Driver didn't return connection info from terminate_connection call."
msgstr ""

